name: CI

env:
  IMAGE_NAME: activemq-artemis-self-provisioning-plugin
  IMAGE_TAG: latest

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.6.2

      - name: Get cache and install dependencies
        uses: ./.github/actions/cache-restore

      - name: Build project
        run: yarn run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Build amd64 image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          archs: amd64
          dockerfiles: |
            ./Dockerfile
            
      - name: Build arm64 image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          archs: arm64
          dockerfiles: |
            ./Dockerfile




